import { Cheese } from './cheese.model';

export const CHEESE: Cheese[] = [
  {
    id: 0,
    name: 'Mamelou',
    category: 'Autre',
    price: 8.1,
    image: 'assets/images/mamelou.jpg',
  },
  {
    id: 1,
    name: 'St-Vergeron',
    category: 'Autre',
    price: 9.25,
    image: 'assets/images/saint-vergeron.jpg',
  },
  {
    id: 2,
    name: "Pont-l'évêque",
    category: 'Vache',
    price: 10.5,
    image: "assets/images/pont-l'eveque.png",
  },
  {
    id: 3,
    name: "Bleu d'Auvergne",
    category: 'Vache',
    price: 13.9,
    image: "assets/images/bleu-d'auvergne.png",
  },
  {
    id: 4,
    name: 'Le Trou du Cru',
    category: 'Vache',
    price: 3.99,
    image: 'assets/images/le-trou-du-cru.jpg',
  },
  {
    id: 5,
    name: 'Belle des champs',
    category: 'Vache',
    price: 7.59,
    image: 'assets/images/belle-des-champs.jpg',
  },
  {
    id: 6,
    name: 'Saint-félicien',
    category: 'Vache',
    price: 5.99,
    image: 'assets/images/saint-felicien.jpg',
  },
  {
    id: 7,
    name: 'Boule des moines',
    category: 'Vache',
    price: 4.05,
    image: 'assets/images/boule-des-moines.jpg',
  },
  {
    id: 8,
    name: 'Crottin de Chavignol',
    category: 'Chèvre',
    price: 4.0,
    image: 'assets/images/crottin-de-chavignol.jpg',
  },
  {
    id: 9,
    name: 'Pélardon',
    category: 'Chèvre',
    price: 3.2,
    image: 'assets/images/pelardon.jpg',
  },
  {
    id: 10,
    name: 'Selles-sur-cher',
    category: 'Chèvre',
    price: 6,
    image: 'assets/images/selles-sur-cher.png',
  },
  {
    id: 11,
    name: 'Taupinette',
    category: 'Chèvre',
    price: 5.9,
    image: 'assets/images/taupinette.jpg',
  },
  {
    id: 12,
    name: 'Rigotte de Pélussin',
    category: 'Chèvre',
    price: 4.51,
    image: 'assets/images/rigotte-de-pelussin.jpg',
  },
  {
    id: 13,
    name: 'Sainte-Maure de Touraine',
    category: 'Chèvre',
    price: 10.3,
    image: 'assets/images/sainte-maure-de-touraine.jpg',
  },
  {
    id: 14,
    name: "P'tit Basque",
    category: 'Brebis',
    price: 20.75,
    image: "assets/images/p'tit-basque.jpeg",
  },
  {
    id: 15,
    name: 'Le Fédou',
    category: 'Brebis',
    price: 6.5,
    image: 'assets/images/fedou.jpg',
  },
  {
    id: 16,
    name: 'Ossau-iraty',
    category: 'Brebis',
    price: 11.35,
    image: 'assets/images/ossau-iraty.jpg',
  },
  {
    id: 17,
    name: "Brin d'amour",
    category: 'Brebis',
    price: 16.0,
    image: "assets/images/brin-d'amour.jpg",
  },
  {
    id: 18,
    name: 'Gabriel Coulet',
    category: 'Brebis',
    price: 30.22,
    image: 'assets/images/gabriel-coulet.jpg',
  },
  {
    id: 19,
    name: 'Ovalie',
    category: 'Brebis',
    price: 6.9,
    image: 'assets/images/Ovalie.jpg',
  },
];
